### ISSUE TITLE
UI and shortcut issues same as D2DX or sven's glide

### ISSUE THREAD

**Issue by shoompaps** [bayaraa/d2gl#1]
Hello,

I've had a run with it and it's looking really good with the HD stuff plus the increased FPS. However, when playing with PD2, these things aren't working still same as d2dx or sven's glidewrapper:

1. buff timers not showing
2. stacking and unstacking runes via shortcut not working (shift+click)
3. quick cast icons not showing (quick cast still works though)

Overall really excited for this and hopefully you're able to fix those and probably use this online in PD2 soon. Thanks a lot!

**Comment by bayaraa** [comment]
yeah i am aware of 1 and 3 but i didn't know about 2.
will try fix everything.

**Comment by shoompaps** [comment]
Thanks! Looking forward to it. Hopefully senpaii from PD2 will contact you. Actually made a video on PD2 subreddit to showcase your mod.

**Comment by bayaraa** [comment]
oh very nice.
just to be curious is your laptop performance mode or saving mode?
also ``ctrl+o`` bring ingame option right? (people telling me it wont).

**Comment by shoompaps** [comment]
Hmm i havent tried using that hotkey as i always ctrl click the settings button. Ill check it after work.

Also my laptop is in performance mode. Here are my specs:

Rtx 3060
Ryzen 7 5800h
16gb ram

**Comment by bayaraa** [comment]
pushed new version.
let me know if its working.

**Comment by shoompaps** [comment]
@bayaraa tried the new version and the issues I posted are all fixed. awesome thank you!

**Comment by bayaraa** [comment]
np! thanks.
