### ISSUE TITLE
will there be compatibility with D2SE modmanager?

### ISSUE THREAD

**Issue by andsimo24** [bayaraa/d2gl#10]

**Comment by bayaraa** [comment]
Never used D2SE before. Will look later!

**Comment by bayaraa** [comment]
@andsimo24 I just tested with D2SE. Unfortunately because of loading DLLs from different location and using different game.exe D2GL won't work with D2SE sorry. Might be can make it compatible with D2SE in the future.

**Comment by dru4a3** [comment]
![11ESR1](https://user-images.githubusercontent.com/17232055/226307643-b477b1ef-97da-4a24-bdae-5f93b57ab2be.png)

Got this screenshot from discord of some d2mod. But the dude (screenshot author) doesn't want to share solution. Just said that he uses a modified d2gl

**Comment by andsimo24** [comment]
> I just tested with D2SE. Unfortunately because of loading DLLs from different location and using different game.exe D2GL won't work with D2SE sorry. Might be can make it compatible with D2SE in the future.

Our programmer rnd2k from the discord community DiabloMods already has adapted D2GL to work with D2SE modmanager. It works fine, although we note the incompatibility of D2GL with some plugins.
https://discord.gg/yPF2ASU

**Comment by bayaraa** [comment]
@andsimo24 good job! wonder how much changes to work with D2SE.

**Comment by bayaraa** [comment]
@rnd2k good job! quite few changes and fixes you found that i can import. very nice.

**Comment by Yoosk** [comment]
The issue is marked as completed but i tried to use latest version with D2SE and it still comes as version not supported.
```
== D2GL v1.3.3 logging started. (2024/1/13) ==

[15:00:32][INFO] Renderer Api: DDraw
[15:00:33][ERROR] Game version is not supported!
```

**Comment by bayaraa** [comment]
Yeah there is already working fork by rnd2k. https://github.com/rnd2k/d2gl

**Comment by Yoosk** [comment]
Which doesn't seem updated, I think it would be easier to add those changes here instead.
