### ISSUE TITLE
Shaders with LF line ending are crashing D2GL

### ISSUE THREAD

**Issue by ajtos** [bayaraa/d2gl#105]
Currently if either `.slangp` or `.slang` files have **LF** line ending, D2GL will just crash on launch. Files with **CRLF** work just fine. Problem is that many shaders default to **LF**, including default Libretro shaders: https://github.com/libretro/slang-shaders (if you download repository as zip).

![screenshot 2023-07-31 152853](https://github.com/bayaraa/d2gl/assets/88950568/0be18985-e75f-4987-b808-2f18c258bddf)

**Comment by bayaraa** [comment]
Fixed in 1.3.2.
