### ISSUE TITLE
Mouse cursor jump issue with unlocked cursor

### ISSUE THREAD

**Issue by BeLikeLeBron** [bayaraa/d2gl#106]
If unlocked cursor is true, mouse has this jumping issue:
1. Keep mouse still
2. Open inventory/quest log/character stats screen
3. Move mouse, it jumps (snaps to center sometimes)

Reproducible and consulted multiple users before submitting issue.
Does not happen with locked cursor.
[see gif](https://cdn.discordapp.com/attachments/115454319993683973/1138975994498256926/Game_W6aIQx5nbg.gif)

Mir Drualga tried some things mentioned in the SlashDiablo discord and mentioned that "this is 100% the problem" 
https://github.com/bayaraa/d2gl/blob/65555c1471f5e2d2f65db8e21e8f49428b9c518f/d2gl/src/win32.cpp#L72

He also mentioned it seems like hardware cursor position is not modified when it would be advantageous to do so. Not sure if that's helpful.

This is a annoying bug. Thanks for reading.

EDIT:

@Hellord. on discord (kr4d github) Has managed to fix this by editing out `&& !App.cursor.unlock` in that line mentioned above.
Not sure if this causes any other issues but it seems to be working so far.

![image](https://github.com/bayaraa/d2gl/assets/5344347/b124bc19-ceb4-4a11-a6e8-ddfdca3849be)

**Comment by bayaraa** [comment]
Fixed in 1.3.2.
