### ISSUE TITLE
how to build sourcecode by myself?

### ISSUE THREAD

**Issue by weili0677** [bayaraa/d2gl#11]
Hi,Mr.bayaraa.
I like your d2gl.
It is use VS2019 or other version to build sourcecode?
I used VS2019 to open sourcecode,It miss some thing.

**Comment by bayaraa** [comment]
Hi.
I use VS2022 with c++20 build tools on windows 10. No extra requirements, just clone, open in VS2022 and build.
There are 3 projects in solution.
- d2gl (shared project used in ddraw, glide3x)
- ddraw
- glide3x

ddraw, glide3x these 2 project you can build.

**Comment by weili0677** [comment]
ok,thank you.I think vs2019 is too low.
