### ISSUE TITLE
graphic bugs on hd4890

### ISSUE THREAD

**Issue by Pokihead** [bayaraa/d2gl#115]
I have in 3dfx mode strange graphical glitches on direct draw they are gone but the shaders shadows are also gone and everything looks the same brightness.
If i move to these glitches they disappear, so they are there just on the edges of the screen.
And they are there to without SlashGaming-Diablo-II-Free-Resolution loaded.
Here are the logs:
[d2gl.log](https://github.com/bayaraa/d2gl/files/12729570/d2gl.log)
[D2230926.txt](https://github.com/bayaraa/d2gl/files/12729571/D2230926.txt)
Here is a Screenshot
![Game 2023-09-26 17-33-43-54](https://github.com/bayaraa/d2gl/assets/37344330/d97cc857-1759-43b5-a319-4fef36a0a7f0)

**Comment by bayaraa** [comment]
I dont own that card so i dont really know whats happening.
Maybe tweaking d2gl graphics setting help?
