### ISSUE TITLE
Bug Report: Fetish Missing Health Bar

### ISSUE THREAD

**Issue by borgdin** [bayaraa/d2gl#116]
This is a HD text bug that occurs only for Act 3 fetish carrying shaman upon its shoulder.  After the shaman is killed, the lesser fetish keeps fighting but the health bar is gone. 

![Missing Health Bar](https://github.com/bayaraa/d2gl/assets/85058545/b35655a5-2754-4c36-a307-df9dffed06d4)

**Comment by ajtos** [comment]
Seems to happen only in HD Text mode.
![Zrzut ekranu 2023-10-27 225652](https://github.com/bayaraa/d2gl/assets/88950568/aa2d83aa-3118-43c4-92a5-ae18cb93db92)
![Zrzut ekranu 2023-10-27 225703](https://github.com/bayaraa/d2gl/assets/88950568/021ce1fd-47f2-4e89-92ae-ba7de76e3da5)

I presume it has issue with all monsters that have SplEndDeath set to 1 in monstats.txt ( 1=spawn the monster in the MINION1 column when they die).

**Comment by Vahsify** [comment]
In the D2SE version, rnd2k fixed this problem.

**Comment by borgdin** [comment]
> In the D2SE version, rnd2k fixed this problem.

D2SE version has the same issue.

**Comment by Vahsify** [comment]
> > In the D2SE version, rnd2k fixed this problem.
> 
> D2SE version has the same issue.

This version: https://mega.nz/file/jCB0gAqK#x_h8Amoa1cFSGUkY3r-9BPqy93qJIBZ9P839OriCuqg

**Comment by borgdin** [comment]
> > > In the D2SE version, rnd2k fixed this problem.
> > 
> > 
> > D2SE version has the same issue.
> 
> This version: https://mega.nz/file/jCB0gAqK#x_h8Amoa1cFSGUkY3r-9BPqy93qJIBZ9P839OriCuqg

The issue is solved. Thanks for your great help.

**Comment by bayaraa** [comment]
Fixed in 1.3.2.
