### ISSUE TITLE
Path of Diablo compatibility issue

### ISSUE THREAD

**Issue by myang26** [bayaraa/d2gl#117]
PTR servers. A1 Inner cloister WP... walk to the stairs. Game crashes reliably. Doesn't happen with other shaders for PoD.

**Comment by myang26** [comment]
![PoD d2gl settings 1](https://github.com/bayaraa/d2gl/assets/86170655/f292b8fe-3334-49bc-9427-887db0d6840d)
![PoD d2gl settings 2](https://github.com/bayaraa/d2gl/assets/86170655/f23d7633-74e9-465c-8c01-79701686799f)
![PoD d2gl settings 3](https://github.com/bayaraa/d2gl/assets/86170655/59a92065-03ed-4694-9152-3514c30b0088)

**Comment by bayaraa** [comment]
POD has own version D2GL. maybe you can report on POD discord.
