### ISSUE TITLE
FSR_RCAS intensity too high

### ISSUE THREAD

**Issue by JH828** [bayaraa/d2gl#119]
Thanks for implementing FSR. :)
0.87 seems to be the default setting for sharpness (at least on Magpie), what D2GL has is 1.0 I believe which results in sharpening artifacts, so think it will look better with the 0.87 setting.

**Comment by bayaraa** [comment]
I dont know Magpie but FSR shader (RetroArch's slang shaders) that d2gl uses RCAS sharpness was 0.2 (lower is sharper).
Now it's 0.3 which is less sharper (since i changes upscale engine in 1.3.2).
