### ISSUE TITLE
Level entry font issue with custom resolution

### ISSUE THREAD

**Issue by skylight102** [bayaraa/d2gl#12]
When I play with 1280 x 720, the text appears twice when entering levels. 

Maybe an option to toggle on/off is possible?

**Comment by bayaraa** [comment]
which version d2 are you running on?

**Comment by skylight102** [comment]
Pd2

**Comment by skylight102** [comment]
Also, whilst I have submitted this request.

Weather doesnt seem to be working correctly on act 5 on pd2 (glide version) 

screenshots using print screen cause a lot of lag, not sure if that is to do with D2GL tho.

Love what you have made here btw <3

**Comment by skylight102** [comment]
![Screenshot004](https://user-images.githubusercontent.com/66263871/223164589-2a23886c-1dd6-4ab4-b186-b8009cc4b10c.png)
1280 x 720 (pd2)

**Comment by skylight102** [comment]
> Entry text bug will be fixed next push. Sorry real busy lately.
> 
> > Weather doesnt seem to be working correctly on act 5 on pd2 (glide version)
> 
> I am aware of this. Will try fix later (not priority tho).
> 
> > screenshots using print screen cause a lot of lag, not sure if that is to do with D2GL tho.
> 
> Is it using d2's ingame screenshot feature?

No worries and thank you! It’s good to see that Senpai from PD2 has reached out also! 

Also, there’s a weird bug on the waypoints that causes the top waypoint to sort of stick closer to the second one. Happens after some time of playing, not sure why.

There is also this bug with the suck/unstuck shortcut, where sometimes it will freeze the game and you’ll be left holding the item you wish to unstack, doesn’t happen too often but the only way to stop it is too leave and rejoin. The item doesn’t vanish tho. I’m aware this is because it’s a super happy fix ^^. 

Thanks so much!

**Comment by bayaraa** [comment]
fixed entry text bug!
btw on 1280 x 720 resolution game looks really nice.
