### ISSUE TITLE
Compatibility for old 32 bit drivers (not opengl 3.3 capable)

### ISSUE THREAD

**Issue by sperez-salgado** [bayaraa/d2gl#120]
Hi, I was wondering whether it is possible to make your wrapper work with drivers not compatible with OpenGL 3.3. I am reviving an old Asus Eee PC Flare using Windows 7 32-bit and the video device driver: Intel Graphics Media Accelerator 3600 Series (v.8.14.8.1096). The video device is the Atom Processor D2xxx/N2xxx Integrated Graphics Controller (Hex PCI IDs 8086:0BE2).

Other wrappers don't work (either too slow or crash), but the -opengl switch makes the game playable.

Thanks in advance.

**Comment by Vahsify** [comment]
Hello. Have you tried Sven's glide? It is also supported by [SlashGaming Diablo II Free Resolution](https://github.com/mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Resolution/releases/tag/3.0.4.0), like D2GL and D2DX. If it does not work correctly, then there is nothing to be done.

**Comment by bayaraa** [comment]
Sorry. It's not possible since some features only available in opengl 3.3 or newer.

**Comment by sperez-salgado** [comment]
> Hello. Have you tried Sven's glide? It is also supported by [SlashGaming Diablo II Free Resolution](https://github.com/mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Resolution/releases/tag/3.0.4.0), like D2GL and D2DX. If it does not work correctly, then there is nothing to be done.

Yes, I did. Alas it crashed.

**Comment by sperez-salgado** [comment]
> Sorry. It's not possible since some features only available in opengl 3.3 or newer.

Thank you for your reply. I understand.
