### ISSUE TITLE
BH settings Monsters color can not visible.

### ISSUE THREAD

**Issue by weili0677** [bayaraa/d2gl#122]
D2DX:
![c0ee012f587dca099d0d17fa52d892c7](https://github.com/bayaraa/d2gl/assets/2888483/528e2d4f-cd9b-40e9-abb4-6cd5fb93b890)
D2GL:
![fec0822402dcca431da789208a47a2c9](https://github.com/bayaraa/d2gl/assets/2888483/b917c888-71c1-438b-8123-8892d2f04d76)

**Comment by bayaraa** [comment]
Yeah it's know issue. Unfortunately hard to fix.
You can disable hd text when you config BH and enable again.
