### ISSUE TITLE
SGD2FreeRes - my D2GL refuses to see it

### ISSUE THREAD

**Issue by VKatilis** [bayaraa/d2gl#124]
Basically what it says - using 3.0.4.0 version.
Run the game - but .json file won't generate for me. 

Any ideas?

**Comment by nelsonmenon** [comment]
Widescreen
D2GL compatible with [SGD2FreeRes](https://github.com/mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Resolution). If you want to play in widescreen download [SGD2FreeRes](https://github.com/mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Resolution) and extract into game folder.
Open d2gl.ini file and set load_dlls_late like below.

load_dlls_late=SGD2FreeRes.dll
If d2gl.ini is not exist run game once it will create one.

Add desired resolution to SGD2FreeResolution.json.
If SGD2FreeResolution.json is not exist run game once it will create one.

**Comment by VKatilis** [comment]
d2gl.ini - that was what I missed.

**Comment by VKatilis** [comment]
> Are you sure you're using d2gl? `CTRL+O` brings up d2gl option?

It's all good, I initially had nothing in load_dlls_late. Have to say, your shader pack is really impressive. Really nice to see FSR there.
