### ISSUE TITLE
Does it make any difference to load dll's early or late?

### ISSUE THREAD

**Issue by malvarenga123** [bayaraa/d2gl#134]
If I load these mods (SGD2FreeRes (3.0.4.0), Plugy (14.0.3), Basemod (1.1.3.9), BH Maphack (1.9.9), d2fps (1.0)), does it make any difference to load them early or late?

Edit: In case anyone is interested, to load Plugy with D2GL, you have to use: PlugY.dll:stdcall:_Init@4

**Comment by bayaraa** [comment]
Probably no difference for those mods.
Since there are some same patch from both d2gl and d2fps, d2fps needs to loaded early in order to work.
