### ISSUE TITLE
 Possible to keep Recording the game window even if the game is minimzed ?

### ISSUE THREAD

**Issue by Ognyan1987** [bayaraa/d2gl#135]
OBS and other recording programs can not detect the game window if it gets minimized  or  dragged  aside to the end of the monitor  ( have not tried to drag it to a second monitor because i dont have )

Other games atleast keep beng recorded if dragged  aside to the end of the monitor  but not D2 with ot without the glide

Is there a way  this can be fixed with the from the glide  , like making  command which tell the game that is not minimized even if it is ?

I have read Ithat **if a game is set to run in full-screen mode, when you alt+tab out the game, it will stop rendering** but it seem in D2 while using D2GL it stops even if the game is minimized or  or  dragged  aside to the end of the monitor  and runs  on Windows mode!

 This would be  good enhancement for streamers or people who like to record their D2 sessions and  by chance  missclick and minimize the game and go afk  !

**Comment by bayaraa** [comment]
No idea if thats possible nor i dont have time for that!
