### ISSUE TITLE
Not an issue - please can someone provide the best Nvidia settings to work best with D2GL

### ISSUE THREAD

**Issue by skylight102** [bayaraa/d2gl#14]
I still experience some small lags when there are large groups of enemies. (PD2).

It used to be much worse, but by altering my nvidia settings, I have improved it somewhat.

Just wondering if someone experienced could screenshot their nvidia settings?

Thanks!

**Comment by skylight102** [comment]
Here are my current settings (RTX 3060)

![1](https://user-images.githubusercontent.com/66263871/223146590-f12eb4cb-1f21-489c-84a4-e4ad10956e47.png)
![2](https://user-images.githubusercontent.com/66263871/223146593-4abbe601-6edb-4f1a-8897-a261ef700be4.png)
![3](https://user-images.githubusercontent.com/66263871/223146594-1080dd13-1f97-42f9-ac12-f8705a383b23.png)

**Comment by xijin1337** [comment]
> I still experience some small lags when there are large groups of enemies. (PD2).
I also experience large fps drops when meeting a large group of enemies. I have already tested different settings, but the drops still occur. In my case, the GPU is Radeon. I think the problem is optimization. However, when comparing D2DX with D2GL, the smoothness of the gameplay is already much greater in favor of D2GL.

**Comment by xijin1337** [comment]
Playing as a necromancer, the frames can go down to 19 per second
![19fps](https://user-images.githubusercontent.com/79951539/223769286-e7f0a220-c0f6-4758-bed7-6da40ec8b06e.png)

**Comment by bayaraa** [comment]
Do you guys playing on laptop?
Because my laptop when its not on performance mode really struggle sometimes.

**Comment by xijin1337** [comment]
@bayaraa 
No, I'm using a desktop computer and a dedicated graphics card. The computer itself is also set to performance mode. 
As for ddraw, I can't run the game in this mode.
![ddraw_startup](https://user-images.githubusercontent.com/79951539/224402331-5d72587e-3814-4d7c-8ba3-84d3267fb98b.jpg)
![specs](https://user-images.githubusercontent.com/79951539/224402370-a1b8a097-1a71-4a14-8d2f-95bca720c635.jpg)

**Comment by skylight102** [comment]
> @bayaraa
> No, I'm using a desktop computer and a dedicated graphics card. The computer itself is also set to performance mode.
> As for ddraw, I can't run the game in this mode.
> EDIT: after running D2VidTst.exe ddraw mode works. I'll let you know if performance improves.
> EDIT2: when ddraw is running smoothness is excellent, no fps drops
> [d2vidtst.zip](https://github.com/bayaraa/d2gl/files/10945172/d2vidtst.zip)
> bayaraa is a great guy :)

I’ve noticed though, when you re-run D2vidTst, it offers you to swap to ddraw again. Does that mean that its setting has reverted? Initially it seemed a major improvement by turning that on, but then the following day (after a pc restart) it was back to lags. Any ideas?
