### ISSUE TITLE
The perspective option generate erroes in some custom maps

### ISSUE THREAD

**Issue by Rayveens** [bayaraa/d2gl#142]
Anyone could tellme how can permanently disable the option of configure the perspective mode? i want to remove it completely and leave it off

**Comment by movomo** [comment]
Video options -> everything: off? I have it disabled as perspective doesn't look pretty on highter than 600p resolution.

**Comment by bayaraa** [comment]
I think there is function (somewhere in d2client) that determine perspective is available or not. If not available it grays out in option menu.
You need to find that function to hook and return false.

**Comment by Rayveens** [comment]
But i'm confused right now, the perspectiva isnt a thing added with the d2gl? Or isnt

**Comment by bayaraa** [comment]
Perspective diablo 2's thing not d2gl. Its available on glide/direct3d video mode.

**Comment by Rayveens** [comment]
okey then, im closing this, i tought it was a d2gl thing that we could perma disable thankyo!.
