### ISSUE TITLE
How can I adjust the thickness of the border for the item description information?

### ISSUE THREAD

**Issue by weili0677** [bayaraa/d2gl#149]
![image](https://github.com/bayaraa/d2gl/assets/2888483/2e455753-870f-45d3-a98f-92904863dd51)
I want to let the border 1px to 2px or 4px.
How can I do?

**Comment by bayaraa** [comment]
That border is part of a shader code. But border code is messy.
https://github.com/bayaraa/d2gl/blob/919df3528de5c5c1b41b326cf68821cd1981c42c/d2gl/src/graphic/shaders/mod.glsl.h#L124

Probably `case 2u:` is item description border iirc.
https://github.com/bayaraa/d2gl/blob/919df3528de5c5c1b41b326cf68821cd1981c42c/d2gl/src/graphic/shaders/mod.glsl.h#L130-L133


pre minified glsl code:
https://github.com/bayaraa/d2gl/blob/919df3528de5c5c1b41b326cf68821cd1981c42c/d2gl/src/graphic/shaders/mod.glsl#L141

**Comment by weili0677** [comment]
Thank you very much!
