### ISSUE TITLE
Sugesstion

### ISSUE THREAD

**Issue by xijin1337** [bayaraa/d2gl#16]
Consider using the Avqest font instead of ExocetBlizzardMedium. In my opinion, the Avqest font is more like the real Diablo font. It would look good after upscaling.
Regards!
[Avqest.zip](https://github.com/bayaraa/d2gl/files/10917699/Avqest.zip)

ExocetBlizzardMedium
![ExocetBlizzardMedium](https://user-images.githubusercontent.com/79951539/223632711-242a0c9d-005a-4ee1-8f45-989c87928139.png)
Avqest
![Avquest](https://user-images.githubusercontent.com/79951539/223632789-1bf1778a-82a9-4b76-aed4-cce9348f77a8.png)
ExocetBlizzardMedium
![ExocetBlizzardMedium](https://user-images.githubusercontent.com/79951539/223779003-a542264f-f1e3-41dd-ab7d-d3cf60e67392.png)
Avqest
![Avqest](https://user-images.githubusercontent.com/79951539/223778988-81e702a6-35dd-4f2d-af39-820246a62b91.png)

**Comment by nelsonmenon** [comment]
how did you get this font to work? i want to test it

**Comment by xijin1337** [comment]
@nelsonmenon 
-extract and drop to the main d2 dir
-go to d2 shortcut properties and 
-add " -direct" line without quotes
[avquest.zip](https://github.com/bayaraa/d2gl/files/10922055/avquest.zip)

**Comment by bayaraa** [comment]
Lately been real busy. Try that font later. maybe add font selection option.

**Comment by skylight102** [comment]
This font is cooler imo, good post!

Thanks for all that you've done bayaraa, it's amazing.

**Comment by jn64** [comment]
This is the site of Graham Meade (GemFonts) who made AvQest: https://moorstation.org/typoasis/designers/gemnew/home.htm

No license stated, nobody cared in those days. There is an email in the "info" link but no idea if it's current.

**Comment by bayaraa** [comment]
Now you can change fonts by yourself.
https://github.com/bayaraa/d2gl/wiki/Features#hd-text-feature
