### ISSUE TITLE
Hi. Mr.bayraa,VS2022 still some wrong.

### ISSUE THREAD

**Issue by weili0677** [bayaraa/d2gl#17]
I installed the VS2022 and open your sourcecode(F:\d2gl\d2gl.sln).
the output information is
```
F:\d2gl\ddraw\ddraw.vcxproj : error  : The imported project "F:\d2gl\d2gl.props" was not found. Confirm that the expression in the Import declaration "..\d2gl.props" is correct, and that the file exists on disk.  F:\d2gl\ddraw\ddraw.vcxproj
```
the Solution Explorer is 
```
d2gl
ddraw(unloaded)
glide3x(unloaded)
```
may be you forgot push some file to github?

>Hi.
>I use VS2022 with c++20 build tools on windows 10. No extra requirements, just clone, open in VS2022 and build.
>There are 3 projects in solution.
>- d2gl (shared project used in ddraw, glide3x)
>- ddraw
>- glide3x
>
>ddraw, glide3x these 2 project you can build.
>
>_Originally posted by @bayaraa in https://github.com/bayaraa/d2gl/issues/11#issuecomment-1454969027_

**Comment by bayaraa** [comment]
Ah i see.
https://github.com/bayaraa/d2gl/blob/39ca47c4e9aa5403ba41e979c970ca941cd982c7/d2gl.props
put this into "F:\d2gl\" and try build again.

**Comment by weili0677** [comment]
> Ah i see. https://github.com/bayaraa/d2gl/blob/39ca47c4e9aa5403ba41e979c970ca941cd982c7/d2gl.props put this into "F:\d2gl" and try build again.

Thank you,It's work.
