### ISSUE TITLE
Reaching out from Project Diablo 2

### ISSUE THREAD

**Issue by senpaisomething** [bayaraa/d2gl#18]
Hi Bayaraa, my name is Senpaisomething and I am one of the developers from Project Diablo 2. I'm reaching out because we're interested in possibly swapping to your d2gl and potentially working with you if that is something you're interested in. If you could reach out to me on discord I'd love to have a chat. My tag is SenpaiSomething#5212

**Comment by bayaraa** [comment]
@senpaisomething Thanks for contact. Sent you request on discord.
My tag is Armin#1889
