### ISSUE TITLE
D2 1.10 Crashes when entering game on newly created single player character in 3DFX mode

### ISSUE THREAD

**Issue by eleriaqueen** [bayaraa/d2gl#2]
Hello, I just tried running 1.10 without mods with your wrapper but the game crashes when entering game with newly created character with the following stack crawl:
```
23:27:28.246  Stack Crawl:
23:27:28.246  Address  Frame    Module       Return    Stack
23:27:28.246  76fafc45 0019eaac USER32.dll   USER32!SetWindowsHookExAW+A835 [omap] 
23:27:28.246  76f889e4 0019eac0 USER32.dll   USER32!wsprintfA+0014 [omap] 
23:27:28.248  6f8a9e71 0019eb08 D2Win.dll    D2Win!Ordinal10115+0311 [omap] 
23:27:28.248  5d775b4f 0019eb84 glide3x.dll  glide3x!setCustomScreenSize+198FF [omap] 
23:27:28.249  763a9062 0019eba0 ucrtbase.dll ucrtbase!get_dstbias+0152 [omap] 
23:27:28.250  763a8ea2 0019ec44 ucrtbase.dll ucrtbase!wcsftime+1772 [omap] 
23:27:28.251  5d7d751f 0019ec5c glide3x.dll  glide3x!grTexDownloadMipMapLevelPartial+70AF [omap] 
23:27:28.251  5d7d7539 0019ecb0 glide3x.dll  glide3x!grTexDownloadMipMapLevelPartial+70C9 [omap] 
23:27:28.252  5d77dd96 0019ecbc glide3x.dll  glide3x!setCustomScreenSize+21B46 [omap] 
23:27:28.252  5d77dd96 00000000 glide3x.dll  glide3x!setCustomScreenSize+21B46 [omap] 
23:27:28.252  Stack walk error: 299
```
I'm attaching full log as well. 
[D2230226.txt](https://github.com/bayaraa/d2gl/files/10834904/D2230226.txt)

CTRL + O works though.

I have a NVidia 1660Ti graphics card by the way.

**Comment by bayaraa** [comment]
hello. It's look like with included freeres mod right.
will look later.
thanks for report.

**Comment by eleriaqueen** [comment]
Yes that's with freeres mod.

**Comment by bayaraa** [comment]
Hey. pushed new version.
let me know it fixed crash.

**Comment by eleriaqueen** [comment]
This crash seems fixed !
D2GL wrapper really introduces never-seen-before features, thanks for providing the community with this neat little nugget.

**Comment by bayaraa** [comment]
nice nice!
#3 did you checked this also?

**Comment by eleriaqueen** [comment]
I checked, but 1.0.2 it doesn't seem to fix any aspect of the issue.
