### ISSUE TITLE
Can add two shaders?

### ISSUE THREAD

**Issue by weili0677** [bayaraa/d2gl#20]
These two shaders：
https://github.com/libretro/glsl-shaders/blob/master/cubic/shaders/cubic.glsl
https://github.com/libretro/glsl-shaders/blob/master/windowed/shaders/jinc2-sharper.glsl
or
How can I made it by myself?

**Comment by bayaraa** [comment]
plan to add feature that load shaders externally in the future!

**Comment by weili0677** [comment]
> plan to add feature that load shaders externally in the future!

Thank you so much.

**Comment by MariusGHub** [comment]
That would be indeed amazing. I use my own CRT-shader.

**Comment by bayaraa** [comment]
this will implemented in the future!
