### ISSUE TITLE
Have some error in windows 7

### ISSUE THREAD

**Issue by weili0677** [bayaraa/d2gl#21]
---------------------------
Windows - 
---------------------------
Exception Processing Message 0xc0000139 Parameters 0x000007FEFD2C819C 0x000007FEFD2C819C 0x000007FEFD2C819C 0x000007FEFD2C819C
---------------------------
OK   
---------------------------

**Comment by xijin1337** [comment]
Unfortunately, the modification is compatible with Windows 10 and higher
![requirements](https://user-images.githubusercontent.com/79951539/224402573-e35a7643-c855-404c-85e6-4708f7bbb8b1.jpg)

**Comment by bayaraa** [comment]
Tbh i never tested on win11 also. I just assuming if it works on win10 probably work on win11.
Will look later that win7 issue.

**Comment by weili0677** [comment]
OK,thanks.I think have more person use windows 7 system.
