### ISSUE TITLE
Can't change font and can't show language other than English for MedianXL

### ISSUE THREAD

**Issue by Nazgulup** [bayaraa/d2gl#24]
Hi, your project works on Median XL very well. But I have two problem. It's only working on the original English version. If I change my game to Chinese. It can't show any Chinese character. Even if I download any Chinese font for the Diablo II. It still not working. Could you advice how could I make working on the Chinese version? Thank you

**Comment by weili0677** [comment]
> Hi, your project works on Median XL very well. But I have two problem. It's only working on the original English version. If I change my game to Chinese. It can't show any Chinese character. Even if I download any Chinese font for the Diablo II. It still not working. Could you advice how could I make working on the Chinese version? Thank you

需要自己研究喽~

**Comment by bayaraa** [comment]
Hi. Currently d2gl only support english version. Maybe in the future add other languages.

**Comment by Nazgulup** [comment]
> Hi. Currently d2gl only support english version. Maybe in the future add other languages.

Actually I found out that don't use the HD font can show the language other than English. The only problem is the font is not clear. I tried to change the font file in the d2gl.mpq but it will show file corrupted. And I'm still looking for the way to make HD Chinese font.

**Comment by Vahsify** [comment]
> Hi. Currently d2gl only support english version. Maybe in the future add other languages.

Hello. Can you please tell how to create these atlases? Or where can I find already created atlases. As I understand it, the difference between fonts without hieroglyphs is not very big.

Many thanks for your work!

**Comment by tytannial** [comment]
> Hi. Currently d2gl only support english version. Maybe in the future add other languages.

In 1.2.0, the language code: SIN=Simplified Chinese, CHI=traditional Chinese
but blz never published Simplified Chinese version officially.

**Comment by bayaraa** [comment]
https://github.com/bayaraa/d2gl/issues/13#issuecomment-1628570836

**Comment by bayaraa** [comment]
multi languages is resloved in v1.2.0.
Other compatibility issues come #13
