### ISSUE TITLE
line 151 error crash 

### ISSUE THREAD

**Issue by germayneng** [bayaraa/d2gl#25]
Hi, 

Really love your work. However, i am facing crashes on the latest 1.0.4 version. The crash seems to be random, but mostly whenever i use a potion on my belt by right clicking it to use it directly on the belt. I have encountered it around 4-5 times in total 

![image](https://user-images.githubusercontent.com/22788747/224757091-f665d0fb-c168-4b87-8dea-7314e1fdf9da.png)
[D2230313.txt](https://github.com/bayaraa/d2gl/files/10959247/D2230313.txt)

version: 1.0.4
plugy offline

**Comment by sweetcarolinahoney** [comment]
Yeah, I had the same random crashes like 2-3 times with line #151 and line #193 errors. Haven't found anything useful on phrozeen keep for these kind of errors.

I also noticed there are options for hd orbs in .ini file. I'm curious if these orbs could use more than default d2 8 bit palettes, so there could be a possibility of using something other than dc6 container. I mean if people could use more than 8 bits, it would really help in creating new UI mods.

Thanks you so much for the great wrapper, looking forward for new updates!

**Comment by bayaraa** [comment]
@deeel1 @germayneng @sweetcarolinahoney could you guys test ddraw mode also if this error occurs.
really dont know if its from wrapper or plugy or something.

**Comment by germayneng** [comment]
i don't think it is specific to plugy. I also dont remember encountering this back crash at earlier v1.0.1 / v1.0.2. The crash is game breaking because since it happens randomly, i have been losing items found in that specific run

**Comment by germayneng** [comment]
i managed to replicate it on ddraw as well. When clicking on potion 

![image](https://user-images.githubusercontent.com/22788747/225059941-8daf85f8-503d-4898-98d3-94e258fa1e7d.png)

**Comment by xijin1337** [comment]
@bayaraa same issue in pd2 on ddraw with plugy

**Comment by bayaraa** [comment]
I cant reproduce that error myself but i think maybe its from stack/unstack fix.
So can you guys test again with these dlls. I removed stack/unstack fix temporarily so stack/unstack wont work.
[D2GL.zip](https://github.com/bayaraa/d2gl/files/10976640/D2GL.zip)

**Comment by deeel1** [comment]
I had a crash with plugy -3dfx on 1.0.4 from yesterday's testing (I attach a file just in case)
but on ddraw without plugy it hasn't happened yet
[D2230314.txt](https://github.com/bayaraa/d2gl/files/10977482/D2230314.txt)

**Comment by deeel1** [comment]
i managed to reproduce it on ddraw without plugy by quickly opening the inventory and then the belt and manually using a potion
[D2230315.txt](https://github.com/bayaraa/d2gl/files/10977655/D2230315.txt)
![2023 03 15  - 1940 -  10-40](https://user-images.githubusercontent.com/79818826/225254416-66c14370-9114-46d0-b9f6-0b6a0dd3d798.png)

**Comment by deeel1** [comment]
> I cant reproduce that error myself but i think maybe its from stack/unstack fix. @deeel1 @germayneng @sweetcarolinahoney @xijin1337 So can you guys test again with these dlls. I removed stack/unstack fix temporarily so stack/unstack wont work. [D2GL.zip](https://github.com/bayaraa/d2gl/files/10976640/D2GL.zip)

I tried the same thing with these .dlls and it doesn't seem to crash, so it must be the stack/unstack fix

**Comment by bayaraa** [comment]
@deeel1 i cant reproduce like insta open inv and use potions etc :P (lot of potion wasted :D)

> I tried the same thing with these .dlls and it doesn't seem to crash, so it must be the stack/unstack fix
seems like it. so please use those dlls few days.

> you can also see grand charm visual bug
yeah currently i cant do anything that visual bug. hope it fixed soon.

**Comment by germayneng** [comment]
Thank you for this temp fix for now. Will test out again to see if it works on my end

**Comment by xijin1337** [comment]
I don't know if it's important, but after installing the fix, error 151 does not occur, but I haven't lost the possibility of stacking/unstacking

**Comment by bayaraa** [comment]
@xijin1337 hmm thats strange.
do you mean unstack/stack shortcut (ctrl+left click/ctrl+shift+left click) working?

**Comment by xijin1337** [comment]
@bayaraa 
I'm very sorry, I thought you were talking about stacking in horadric cube.
I didn't even know such a shortcut existed.

**Comment by bayaraa** [comment]
@xijin1337 its ok. yeah horadric work normally. only shortcuts wont work.

**Comment by weili0677** [comment]
this crash is fix show pd2 skill icons reason.
You need edit the D2Glide.dll file offset 0x7854 "0x7E" to "0xEB" in -3dfx mode。It's maybe draw image bugs stuff.

> @xijin1337 its ok. yeah horadric work normally. only shortcuts wont work.
