### ISSUE TITLE
ReShade (32-bit, OpenGL mode) crashes on Mac Crossover

### ISSUE THREAD

**Issue by odt1** [bayaraa/d2gl#26]
![Screenshot 2023-03-14 at 12 01 45](https://user-images.githubusercontent.com/33424002/224951308-94c4ea9f-536c-4208-a23b-6e670bdca9e0.png)

Tried changing opengl version in config, same error.

To enable reshade in Crossover, unpack its installer with Keka, take 32bit lib, rename to opengl32.dll and drop to game folder. Also it needs d3dcompiler_47.dll (32bit) and both libs to be set to native overwrite in wine config for it to load, launch game with -3dfx. This setup worked with d2dx.

Logs: [reshade.zip](https://github.com/bayaraa/d2gl/files/10966480/reshade.zip)

p.s. Thank you for making this, amazing work so far! <3

**Comment by bayaraa** [comment]
hello.
Ah, I didn't tried reshade yet (not even on windows).
Will see later whats going on.

**Comment by bayaraa** [comment]
Just tried reshade on macos (wine). Reshade requires opengl 4.3, but macos has only 4.1 so opengl reshade wont work on macos. Therefore closing this issue.
