### ISSUE TITLE
Enhancement request

### ISSUE THREAD

**Issue by KevTheDankest** [bayaraa/d2gl#27]
Please add 1280x720 resolution, I am trying to get the zoomed out view like on D2DX.

Thank you for all your hard work!

**Comment by bayaraa** [comment]
you can add custom resolution in SGD2FreeResolution.json like this 
![](https://i.gyazo.com/9703a3ac6ca99d4cc3eaa89837e1dc92.png)

**Comment by KevTheDankest** [comment]
Wow, thank you very much! It worked!
