### ISSUE TITLE
Glide mode on Win 10 and PD2 crashes on maps an randomly

### ISSUE THREAD

**Issue by unpapardo** [bayaraa/d2gl#28]
I can not replicate reliably the crash, but it crashes randomly with ACCESS VIOLATION 00005 or eventually Line 151 error codes. If it works for something, during the crash the screen zooms in the lower left quarter of the screen.
Sometimes it works for hours and sometimes it crashes within minutes, during normal gameplay, so the trigger is hard to diagnose. With the Ruined Cistern map in PD2, however, it would crash every time, but still, sometimes near the beginning, sometimes in the middle or in the end.
The game doesn't crash with the bundled PD2 wrappers nor with d2dx, so it's definitely the interaction with d2gl

I really want this mod to work without crashes, as it looks absolutely beautiful, almost like a new game with the HD fonts. But the constant crashing is messing up with my holy grail attempts big time

**Comment by bayaraa** [comment]
#25 is this similar?
https://github.com/bayaraa/d2gl/issues/25#issuecomment-1469419207
you can try stack/unstack disabled dll.

**Comment by unpapardo** [comment]
Well, I tried it and after a while it did crash, but just not catastrophically. It just started flickering the desktop black while the sound was still playing, but no error code

**Comment by bayaraa** [comment]
Sounds like driver issue. Any change to enable `use_compute_shader` in ini file. Whats your pc specs?
Also could you upload D2's log file `D2230323.txt` like this in D2 folder.

**Comment by unpapardo** [comment]
I thought it was running fine after changing the compute shader setting, but no, it still crashes eventually with ACCESS VIOLATION 00005 error code.

My PC is a i3 7100 with Intel HD 630 graphics, 24gb RAM and on Win 10. For what is worth, I also installed this (Game + PD2 + Plugy) on my dad's laptop and it crashes just the same

[D2230325.txt](https://github.com/bayaraa/d2gl/files/11070437/D2230325.txt)

**Comment by Ognyan1987** [comment]
Any fix here , i am also getting crashes like those !?

**Comment by bayaraa** [comment]
PD2 season 7 already using D2GL.
