### ISSUE TITLE
Am I loser for checking if there is an update every day? :D Hope all is good Bayaraa!

### ISSUE THREAD

**Issue by skylight102** [bayaraa/d2gl#29]
Keep up the good work! <3

**Comment by bayaraa** [comment]
yeah every day is kinda lot (been busy lately). check weekly at least lol :P

**Comment by skylight102** [comment]
> yeah every day is kinda lot (been busy lately). check weekly at least lol :P

Damn, I thought so I might be. :(

I can cut down to once every 2 days, final offer. :P
