### ISSUE TITLE
Selecting skill-delay

### ISSUE THREAD

**Issue by MariusGHub** [bayaraa/d2gl#30]
Dear Bayaraa,

I noticed that selecting skills, like when you're being attacked has some slight of delay. Without this mod there's no delay. I think it might be related to the fps + fast hit recovery? Was using Ddraw. 

Kind regards,
Marius

**Comment by MariusGHub** [comment]
Dear Bayaraa,

Yes. Just the regular left or right-clicking and selecting the skill with either F1 or another button. I think the fps sort of bugs out the FHR. But I think you know it better than me. So far this mod looks really awesome.

**Comment by bayaraa** [comment]
Unlocked fps and motion prediction only affect drawing more images between. I don't think its affect FHR etc.
Maybe v-sync causes input lag or something? Try turn v-sync off and enable foreground fps and set to your display refresh rate.
Otherwise i really don't know.

**Comment by MariusGHub** [comment]
Goodday Bayaraa,

I wil do some more testing then jsut in case. I might suspect it could be my basemod interfering, maybe the 25fps bypass or something else or indeed the v-sync, etc.

**Comment by bayaraa** [comment]
Really don't know. I think it's not D2GL issue. Maybe with increased fps more often notice FHR.
