### ISSUE TITLE
Game crashing entering furnace of pain

### ISSUE THREAD

**Issue by prrrzzzz** [bayaraa/d2gl#31]
I'm doing some mini ubering right now. Did get a line #1336 exactly upon entering the portal.
https://github.com/prrrzzzz/D2230322

**Comment by bayaraa** [comment]
this occurs both (glide, ddraw) wrappers?
also PD2 season 4?

**Comment by prrrzzzz** [comment]
I can only run the game with the -3dfx command in the plugy shortcut (so glide?), with the other wrapper I cannot open a game without getting unhandled exception errors for any character. 
Also this is not a common crash at all.

The name of the folder is just very old, I run a fairly up to date version of the s6 game.

Also I just saw in the file you can see, sometimes after getting ye olde line 15 error I cannot enter games with any characters and ended up restarting my computer, then it worked fine. Sometimes I just get two or three of those and then it works though.

**Comment by Ognyan1987** [comment]
Excuse me !  What is the command for enabling ddraw ? For glide is `-3dfx` and what is for Ddraw?
Thanks!

**Comment by bayaraa** [comment]
https://github.com/bayaraa/d2gl/wiki/Installation

**Comment by bayaraa** [comment]
Try new version. otherwise not really know cause.
