### ISSUE TITLE
This map/skill icon issue can be pretty wacky at times.

### ISSUE THREAD

**Issue by skylight102** [bayaraa/d2gl#34]
![image](https://user-images.githubusercontent.com/66263871/229314306-f3bfb793-b48d-43dc-86cc-feced7149ce0.png)

Sometimes it shows 100 heads along the river in act 1, all the waypoints have changed to skills etc.

**Comment by eleriaqueen** [comment]
What game version, what mod ?

**Comment by bayaraa** [comment]
@skylight102 it will be fixed in season 7.

**Comment by skylight102** [comment]
> @skylight102 it will be fixed in season 7.

Great work. Will it still work for older versions? I only play season 5 you see :)
