### ISSUE TITLE
Feature request/question: Unlocked mouse

### ISSUE THREAD

**Issue by sajber** [bayaraa/d2gl#35]
Hi, d2gl is awesome man, great job and thanks a lot!

Wondering if it's possible to get an "unlock mouse" feature when using windowed mode? That was my preference with ddraw.
I did notice that opening the settings menu with ctrl+o does indeed unlock the mouse so hopefully it wouldn't be super tricky.

Thanks for all the work!

**Comment by bayaraa** [comment]
new version added cursor unlock feature!
