### ISSUE TITLE
Second monitor black screen with D2GL

### ISSUE THREAD

**Issue by FlyersD2** [bayaraa/d2gl#36]
Hey bayaraa i ran into 2 problems with D2GL on Path of Diablo. 

Everytime i start the game my second monitor turns into a black screen but i can still interact with the apps that are running on that screen. The only thing that can show up over the black screen is the start menu like this : https://i.imgur.com/pQekkIr.jpg
I've tried running the game windowed, fullscreen, changing random settings and even reinstalling PoD but nothing worked. I asked around in the discord but nobody had this problem.

My other issue is the mouse jumping every time you open your inventory or stat screen. It's not that bad in fullscreen but in windowed mode the cursor basically jumps to the edge of the game window, i know this is a common issue with glide so i was wondering if you had a fix for it 😄

**Comment by bayaraa** [comment]
Pushed new release with some multi monitor fixes. Let me know if your issue fixed.
Not sure how to fix cursor issue tho.

**Comment by Ognyan1987** [comment]
Same situation here but instead of second monitor i  load the gam through loader with -ns option
game opens black at the boot no matter if window mode or full screen

@FlyersD2  does your monitor got sound?

**Comment by FlyersD2** [comment]
@bayaraa 
My issue is now fixed, not really sure what was the problem but i changed a bunch of settings in Glide then ran the "Test" in fullscreen mode, after that D2GL worked as intended. 
I then reverted the settings back to their original values and still worked... i'm 99% sure i ran the Test in Glide before when i was looking for a fix but always in windowed mode so maybe running the Test in fullscreen was the fix ???

Anyways, glad i can enjoy D2GL now  ❤️
