### ISSUE TITLE
Feature request: custom LUT images

### ISSUE THREAD

**Issue by paul-pumphut** [bayaraa/d2gl#37]
First of all, thank a lot for your work, it is amazing!
Is it possible to add loading custom LUT images?

**Comment by bayaraa** [comment]
what is GLUT images?

**Comment by paul-pumphut** [comment]
Yes, sorry, I meant LUTs )

**Comment by paul-pumphut** [comment]
Thank you for your explanation. That's all I need to know.

**Comment by StudioPetrikas** [comment]
I can't seem to figure out the 'custom' LUT loading. Once ran with "-direct" I can see that my LUT takes effect, but it has added effect of "Colour 1" to "Colour 14". "Game Default" stays "Game Default" and does not load the custom LUT. 

Is there a way to load it "clean", without the added effects of "Colour 1 to 14"?
