### ISSUE TITLE
Fullscreen Windowed Mode

### ISSUE THREAD

**Issue by whipowill** [bayaraa/d2gl#39]
This is great, thanks for all your work.  I've been experimenting w/ the settings and I'm finding that windowed mode performs much better for me than fullscreen.  I'm wondering if you might be able to add a "windowed-fullscreen" mode that blends the two.  I don't know why the game plays so much better in windowed mode but it does -- much fewer stutters, less input lag on vsync, and more consistent smooth FPS.

**Comment by bayaraa** [comment]
Fullscreen is actually borderless-windowed. You can increase window size (custom size) in the screen option.

**Comment by whipowill** [comment]
I got it working, my mistake.  Had to put the game into hi performance mode.  This is a great resource you've made, many thanks!
