### ISSUE TITLE
Install into my PD2 Folder Removes 1068x600 resolution option

### ISSUE THREAD

**Issue by wkelly33** [bayaraa/d2gl#40]
Dropping the files as directed in readme removes the option to adjust resolution to 1068x600. Tried with and without plugy. Only 640x480 and 800x600 are available.

**Comment by bayaraa** [comment]
What is your windows version?
Run game.exe with `-3dfx -log` flag so it creates `d2gl.log` file. Please post here with d2 log file (`D2230411.txt`).

**Comment by oGkspAz** [comment]
If you did what I did and removed the old version files first, make sure you have a d2gl.ini in the folder.

**Comment by wkelly33** [comment]
Windows 10

relevant lines from that file include the below. I dont have nearly as much data showing in there like turokhc even though the game did get the same access violation.
21:27:52.063  imagehlp.dll loaded for better stack crawls.
21:27:52.486  ........DirectSound progress: 0 buffers available is less than min needed 16 buffers for 3d sound
21:27:52.492  ........DirectSound progress: 0 buffers available is less than min needed 16 buffers for 3d sound

**Comment by bayaraa** [comment]
PD2 season 7 already using D2GL.
But for older season you need to add widescreen yourself.
https://github.com/bayaraa/d2gl/wiki/Installation#widescreen
closing it for now.
