### ISSUE TITLE
UNHANDLED EXCEPTION: ACCESS_VIOLATION (c0000005)

### ISSUE THREAD

**Issue by turokhc** [bayaraa/d2gl#43]
More than often getting this message, tried to move the diablo folder around without success.

**Comment by turokhc** [comment]
I might have found a solution: editing the regedit diablo II.exe path. Waiting for somebody with the same problem to confirm

**Comment by skylight102** [comment]
What do you mean editing the path, can u explain more please? I am having issues with the new version

**Comment by turokhc** [comment]
In the regedit I had a different path in the one that redirects t

**Comment by bayaraa** [comment]
sorry to late reply.
https://github.com/bayaraa/d2gl/issues/40#issuecomment-1502319814 saw your submit and first few crashes related to antivirus(bitdefender) maybe?
can i ask what gpu your pc has?

**Comment by turokhc** [comment]
intel hd graphics 5500
