### ISSUE TITLE
Can adjust the font size

### ISSUE THREAD

**Issue by qwertyue** [bayaraa/d2gl#44]
Hope to support font size adjustment

Because the font is really too small at 100% scale

**Comment by bayaraa** [comment]
What font size? In-game texts? or D2GL options font size?

**Comment by qwertyue** [comment]
> What font size? In-game texts? or D2GL options font size?

YEP, In-game texts, such as the monster name on hp bar

**Comment by Rayveens** [comment]
i would like an option to disale the monster hoover, or since im using custom monster bars, and sadly the hd fonts repalces it.

**Comment by qwertyue** [comment]
Monster names are just an example, d2gl used its own way to render the fonts on the game interface, and I wanted to be able to adjust the font size freely.
Because at higher resolutions (1600x1000), the current font looks laborious (because it's too small).

**Comment by bayaraa** [comment]
I make HD font sizes match original font sizes. It's quite work to change in-game font sizes.
Even increases size it won't look good because i can't increase UI sizes.

**Comment by bayaraa** [comment]
> i would like an option to disale the monster hoover, or since im using custom monster bars, and sadly the hd fonts repalces it. https://files.fm/f/egdg9f839

i will see what i can.

**Comment by Rayveens** [comment]
> > i would like an option to disale the monster hoover, or since im using custom monster bars, and sadly the hd fonts repalces it. https://files.fm/f/egdg9f839
> 
> i will see what i can.

Thank You greatly appreciated

**Comment by bayaraa** [comment]
@Rayveens ty! feel free to add me on discord Armin#1889. I might have request for you aswell 👍

**Comment by qwertyue** [comment]
> I make HD font sizes match original font sizes. It's quite work to change in-game font sizes. Even increases size it won't look good because i can't increase UI sizes.

maybe the font size can be adjusted . from 13 to 15

**Comment by Ognyan1987** [comment]
I guess increasing the size of the d2gl HD font size will do the work

**Comment by Rayveens** [comment]
> @Rayveens ty! feel free to add me on discord Armin#1889. I might have request for you aswell 👍

I send you a friend req on discord RayveeN#4104 feel free yo aceptme when you get the time.
