### ISSUE TITLE
Perspective Mode

### ISSUE THREAD

**Issue by whipowill** [bayaraa/d2gl#46]
Was perspective mode always this awesome or did you do something to improve it?  I've never used it in my life but I tried it and it's amazing.  Also major props for making this work on Wine.  It plays better on my Linux laptop now than my Windows machine.

**Comment by Ognyan1987** [comment]
As far as i know it was always like that , i always use it !

**Comment by bayaraa** [comment]
> Was perspective mode always this awesome or did you do something to improve it? I've never used it in my life but I tried it and it's amazing. Also major props for making this work on Wine. It plays better on my Linux laptop now than my Windows machine.

Nothing except just some artifact fix for perspective image drawing.
Surprisingly did nothing particular for wine :D.
Latest wine or wine based compatibility layers are awesome. specially in linux.
