### ISSUE TITLE
Opening the game with `-ns`  causes black screen

### ISSUE THREAD

**Issue by Ognyan1987** [bayaraa/d2gl#48]
Hello! 
I saw your project yesterday  using it on D2 Lod 1.13d - 1.14d and i wanted to give it a go i like it pretty much but it has some minor stuff which can be added or fixed !?  :)

- Issue , Starting the game through loader with  no sound ( -ns ) causes black screen, however if i enable the sound it loads fine through the loader. Maybe u can add -ns option on/off into the d2gl  settings so it can be used instead ?

- Issue , Colour Grading and Bloom Effect  causes black spots inside stash and cube or coloured spots at vendors
![Colour Grading and Bloom Effec predict black spots](https://user-images.githubusercontent.com/59932856/231654629-e082a819-3767-43ea-8f5e-40d621597fe6.png)  
![Uploading Colour Grading and Bloom Effect black spots vendors.png…]()

- Possibility to use ` -notfiaspect ` option which streches the screen when users go full screen ( it will remove the black bars when full screened)

**Comment by bayaraa** [comment]
hmm -ns makes black screen is strange. is used -ns all the time bot wrapper works normally on 1.13d/1.14d.
have no idea black rect on stash panel. do you include other mods?
I might add viewport stretch option (since there are people also wants).

> Possibility to increase the game window size with out this to take automatically effect on next start ups of the game but only at the current game window made on. If the game is started again or other clients are opened window size to go/remain 800/600 there by default! Example: On Game Instance 1 i want 1024/768 WIndow size but the next Instance 2 i load to remain 800/600 and not to use the changes 1024/768 i made on Instance 1

i don't think add this. (not sure why you want 2 instance)

**Comment by Ognyan1987** [comment]
- If u can add -ns into d2gl  to be turned on and off same as full screen that migjt fix the issue

- well i use 2 instances of the game for Bo barb

**Comment by Ognyan1987** [comment]
EDIT: It seem the Colour Grading is the reason for the black spots from the screenshots and not the motion prediction as i thought! Disabling Colour Grading removes the black spots!
i Edited my previous post aswell .
