### ISSUE TITLE
Unsupported Glide3x.dll - Release v1.1.1

### ISSUE THREAD

**Issue by D2R-Gimli** [bayaraa/d2gl#50]
I extracted the release files to my pd2 dir.
I made a shortcut of game.exe and added -3dfx and -log
When i start it, i get this error message and the log file is empty.

![image](https://user-images.githubusercontent.com/119764208/232207223-fcf5b464-9af0-4756-9c52-67f57b3d5d48.png)

I have DirectX12, desktop-pc which is really strong GTX 3080Ti etc..

**Comment by bayaraa** [comment]
delete or rename D2HD.dll.
And if you want widescreen https://github.com/bayaraa/d2gl/wiki/Installation
