### ISSUE TITLE
Inventory clipped

### ISSUE THREAD

**Issue by Akenathos** [bayaraa/d2gl#51]
Hi, before all, great work! I'm having a trouble with the inventory screen, its clipped. I try all resolutions and the issue persist. I perform a clean installation.

![img](https://user-images.githubusercontent.com/130929680/232335927-39c8ff7b-6df7-4d8d-bbe8-0383f82d483d.png)

Thanks for your time and sorry about my English, I'm from Argentina.

**Comment by Ognyan1987** [comment]
Have you edited Colour Grading or  Bloom effect ?

**Comment by Akenathos** [comment]
> Have you edited Colour Grading or Bloom effect ?

I dont touch any option, or edit any file. Clean installation and play.

**Comment by Akenathos** [comment]
> ```ini
> SGD2FreeRes.dll
> ```

Thank you so much! Work's flawlessly
