### ISSUE TITLE
Cursor not active when switch back to game.

### ISSUE THREAD

**Issue by kr4d** [bayaraa/d2gl#52]
D2GL is a great wrapper, as I first saw d2dx, that's awesome. TY bayaraa.
I've test for a few days with ver 1.13c on SlashDiablo server, so far so good, no issues except this.
ATT, Cursor not active when switch back to game from other window, need to mouse click then cursor will active. 
don't know whether it's a issue.

**Comment by Ognyan1987** [comment]
I was Planning to make  similar topic ! 
I use to play windows mode on my private 1.13d server !
When i switch back to the D2 window i get the desktop cursor and ingame cursor bound together , i need to click once  somewhere inside  the D2 window so the desktop cursot to dissappear and  click 1 more time ingame to activate the ingame cursor , which is abit annoying :)

**Comment by weili0677** [comment]
This is tiny bug...ignore it.

**Comment by bayaraa** [comment]
this should fixed in v1.1.2
