### ISSUE TITLE
question

### ISSUE THREAD

**Issue by xijin1337** [bayaraa/d2gl#54]
When I heard you were working on center-placed orbs, one thought came to mind. Could you modify the inventory screen slightly to fit all PlugY keys, (if it doesn't conflict with the design of center-placed orbs, of course)? Moving around would be much easier and inventory would look more aesthetically pleasing.
Regards!
![image](https://user-images.githubusercontent.com/79951539/233506542-1c12107a-9b09-47d6-9821-3c72a4c45f8b.jpg)

**Comment by xijin1337** [comment]
I dream that the joint actions of Barayaa and SenpaiSomething would to bring such effects :
![1](https://user-images.githubusercontent.com/79951539/233513446-a985da25-28a2-4a7f-9d98-24bb8a44cb67.png)
![2](https://user-images.githubusercontent.com/79951539/233513472-97e12267-8c53-4fea-ba1d-e580d71b6b31.jpg)
![3whenparty](https://user-images.githubusercontent.com/79951539/233513484-fe75a281-fd45-484e-b919-ec8ff1511d85.jpg)
The culmination of all this could be the option to choose between the BlizzardExocet and AvQest font :)
Thank you and congratulations for what you do. Well done.

**Comment by xijin1337** [comment]
pictures for reference, don't laugh :)

**Comment by bayaraa** [comment]
oh my :D
i dunno man changing and moving ui things is really not easy task.
maybe that plugy ui thing i might be able make seperate dll to fix.
AvQest font i will look into.

**Comment by xijin1337** [comment]
@bayaraa 
I wanted to know if that's even possible and I had to ask about it. So we need to find some magician who doesn't know it's hard :D
thanks for remembering about AvQest
