### ISSUE TITLE
Widescreen crashes on macos+wine

### ISSUE THREAD

**Issue by markusjohnsson** [bayaraa/d2gl#56]
d2gl works fine on macos+wine. However, if i try to enable SGD2FreeRes, it crashes when I enter a game (menus work fine). I've gotten it to work on Windows, so my ini is correct I think.

I have no idea how to test SGD2FreeRes without d2gl, that is why I open the issue here. It crashes both with SGD2FreeRes provided by d2gl 1.1.1 and with the 3.0.4.0 version.

I have an older version of PD2 (Season 4) where widescreen works. It contains a SGD2FreeDisplayFix.dll (but this is without d2gl). 

I've also tried to build SGD2FreeRes from sources (from bayaraa/SlashGaming-Diablo-II-Free-Resolution) but couldn't get it to compile (on Windows with VS 2022). I found no docs for building it, I just ran cmake to generate project files and then tried to build in VS. If I can get it to compile perhaps I can assist with debugging the issue. 

These are from a run with just D2 LoD + d2gl + SGD2FreeRes (no PlugY or PD2):

[d2gl.log](https://github.com/bayaraa/d2gl/files/11334711/d2gl.log)
[Crash.txt](https://github.com/bayaraa/d2gl/files/11334701/Crash.txt)
[D2230426.txt](https://github.com/bayaraa/d2gl/files/11334702/D2230426.txt)

**Comment by markusjohnsson** [comment]
OK, so it is a known issue then. If you have any pointers on how I can debug the issue, or how to build SGD2FreeRes.dll from source, I'll be glad to help getting it fixed.

**Comment by bayaraa** [comment]
I used vscode with cmake, c++ extensions installed.
Also it requires NASM https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win32/

Even tho with debug dll, i dont know how to debug in wine so.
The thing is D2GL+Sgd2FreeRes works flawlessly on crossover win10 32bit bottle tho.

**Comment by bayaraa** [comment]
It seems no more crashes on latest release of winecx.
https://github.com/Gcenx/winecx/releases
