### ISSUE TITLE
D2gl 1.1.2  questiom

### ISSUE THREAD

**Issue by Ognyan1987** [bayaraa/d2gl#59]
where is this part located ?

Added: load different config file (command line: -config custom loads d2gl_custom.ini).
You can run same game.exe but different config file.

Does this mean we can add  all the command  lines as -3dfx -diect -txt ect...  inside  this custom d2gl.ini instead of at the end of the game.xe target?

**Comment by bayaraa** [comment]
yeah  
shortcut 1: `-3dfx -direct -txt` opens game with default `d2gl.ini` config
shortcut 2: `-3dfx -direct -txt -config conf1` opens game with `d2gl_conf1.ini` config  
which is you can run same exe but 2 different config file.

**Comment by Ognyan1987** [comment]
> yeah shortcut 1: `-3dfx -direct -txt` opens game with default `d2gl.ini` config shortcut 2: `-3dfx -direct -txt -config conf1` opens game with `d2gl_conf1.ini` config which is you can run same exe but 2 different config file.

Can i put the command lines inside  the default  `d2gl.ini`  like  Command line= -3dfx -direct -txt ...... ` and just use the regular non shortcuted game.exe as usual?

**Comment by bayaraa** [comment]
No. It's command line arguments not config.
If you want different config for each window use command line for different configuration.

**Comment by Ognyan1987** [comment]
> No. It's command line arguments not config. If you want different config for each window use command line (create shortcut for plugy.exe).

Do you have any plans to add it as a command line option inside d2gl.ini ?

**Comment by bayaraa** [comment]
There is no launcher with D2GL so it's impossible to add command line arguments in config file like plugy.

**Comment by Ognyan1987** [comment]
> There is no separate launcher for D2GL so it's impossible to add command line arguments in config file like plugy.

hmm , i  mean commands  like the windows mode u added 
`; Game will run in fullscreen window.
fullscreen=false`  ->  that mean   `-w` 

so adding stuff like this 

`; Game will run with sound 
ingamesound=false` -> means  `-ns`

or

;Game will use direct txt
directtxt= true - > mean ' -direct -txt'

or

;Game picture will strech shile full screened
aspectratio= true -> mean `-notfixaspect`
