### ISSUE TITLE
Bug found while playing PD2 Plugy

### ISSUE THREAD

**Issue by sccmac** [bayaraa/d2gl#6]
Played a game with the v1.0.2 patch, took a break and when I came back the full rejuv pots and 35% rejuv pots were bugged and looked like this: https://imgur.com/a/Ttdyln4 . Only thing out of the ordinary that I did was making sure I had CTA equipped upon exit, since there's a bug with CTA and PD2 Plugy, making CTA skills unusable. I was playing a rabies druid and the skill icons on the rejuv pots were part of the quick cast skill bar.

**Comment by bayaraa** [comment]
Ahh, i found that bug too. Unfortunately right now i cant do anything about it sorry.
I think D2Glide.dll has some bugs or something. On this issue directly PD2 devs investigate better since its from pd2's buff timer, quick cast bar drawing.
But ddraw mode doesnt have this issue (certainly from my testing).

**Comment by deeel1** [comment]
https://imgur.com/a/TePMcAi

**Comment by bayaraa** [comment]
look at that run/walk button too 😅

**Comment by shoompaps** [comment]
Just had that issue as well. Lol

**Comment by deeel1** [comment]
yeah, I noticed this only after I recorded the video, then started assigning other skills and they began to be reassigned to the different icons (like "New Stats" button) in the same manner

the same can also happen with the map, that is, some icons on the map will have the appearance of a skill, etc
I didn't notice a clear pattern by which this happens, it's quite random and in general doesn't break the game

**Comment by skylight102** [comment]
Theres quite a few like this,

So i have had waypoints turn into charms, my head appear 1000 times along act 1 river.
