### ISSUE TITLE
D2GL v1.1.2 texture issue on AMD Mobility Radeon HD 5000 series

### ISSUE THREAD

**Issue by Vahsify** [bayaraa/d2gl#60]
Greetings! 

Found a texture issue on the AMD Mobility Radeon HD 5000 discrete graphics card.

![Mt0yngPcznc](https://user-images.githubusercontent.com/105426840/235327262-f5887b98-7968-4939-920f-249ba03fcd2d.jpg)

Tested on Windows 7 as well as on Windows 10 on the same laptop. The problem is on both 7 and 10. 

Video from D2GL was not captured, but it was captured from D2DX and D2DX worked correctly. 

[Video](https://youtu.be/ql46OHNumKs)

![rGnD8YnaJPE](https://user-images.githubusercontent.com/105426840/235328420-f4a8715f-c4ff-41cb-9acc-dca3ada2656c.jpg)
![e5ZjUkoO284](https://user-images.githubusercontent.com/105426840/235328422-b0e54930-83ea-4bb9-aae6-95e7e9fec226.jpg)

Log files: 
[D2230430.txt](https://github.com/bayaraa/d2gl/files/11360243/D2230430.txt)
[d2gl.log](https://github.com/bayaraa/d2gl/files/11360244/d2gl.log)

**Comment by Ognyan1987** [comment]
Have you by chance enabled Colour Grading or Bloom Effect cause this is what causes similar black spots to me

**Comment by bayaraa** [comment]
Hi there!
Is older version (1.0.4 for instance) running normal?

**Comment by Vahsify** [comment]
> Have you by chance enabled Colour Grading or Bloom Effect cause this is what causes similar black spots to me

No, Color Grading and Bloom Effect are disabled, enabling/disabling has no effect on the issue.

**Comment by Vahsify** [comment]
> Is older version (1.0.4 for instance) running normal?

Yes, in version 1.0.4 everything works correctly. This problem starts in version 1.1.1.

**Comment by Vahsify** [comment]
> Is older version (1.0.4 for instance) running normal?

Maybe it will help, in version 1.0.0 to 1.0.2 inclusive, a slightly similar problem was with HD elements.

![nNFJdcS0xuE](https://user-images.githubusercontent.com/105426840/235357088-82e54c0a-8276-42c8-a79d-a32212cbb777.jpg)

**Comment by Ognyan1987** [comment]
Similar  situation here with 1.1.1 and 1.1.2    but my comes from enabling Bloom Effect or Colour grading 
With 1.0.4  all was fine  even with Bloom and Grading enabled , is there a possible fix u can do @bayaraa 
![blak spoooot1](https://user-images.githubusercontent.com/59932856/235373067-ad68caa6-6840-4dea-832f-facf74b86f2b.png)
![Motiojn predict black spots](https://user-images.githubusercontent.com/59932856/235373076-27676600-555d-4d63-a5c3-5325bfb86037.png)

**Comment by bayaraa** [comment]
@Vahsify Could you try this build if its fixed your issue.
[glide3x.zip](https://github.com/bayaraa/d2gl/files/11364545/glide3x.zip)

**Comment by Vahsify** [comment]
> @Vahsify Could you try this build if its fixed your issue.
> [glide3x.zip](https://github.com/bayaraa/d2gl/files/11364545/glide3x.zip)

The graphical issue has not changed.

**Comment by bayaraa** [comment]
[glide3x.zip](https://github.com/bayaraa/d2gl/files/11364956/glide3x.zip)
What about this one?

**Comment by Vahsify** [comment]
> What about this one?

The graphical issue still hasn't changed.

**Comment by bayaraa** [comment]
run with `-3dfx -log` and provide me `d2gl.log` please.

**Comment by Vahsify** [comment]
> run with `-3dfx -log` and provide me `d2gl.log` please.

[d2gl.log](https://github.com/bayaraa/d2gl/files/11365062/d2gl.log)

**Comment by Ognyan1987** [comment]
Here is also my witht he latest glide u provided here if that matters -> 
[d2gl.log](https://github.com/bayaraa/d2gl/files/11365195/d2gl.log)

**Comment by bayaraa** [comment]
oh my. without real hardware is not easy to find the cause. :(
is your gpu drivers updated right?

**Comment by Vahsify** [comment]
> is your gpu drivers updated right?

Yes, the GPU driver has been updated using Windows 10 Update Center.

**Comment by bayaraa** [comment]
How about ddraw mode?

**Comment by Vahsify** [comment]
> How about ddraw mode?

If you mean HD text, HD cursor and minimap:
![J91m_G2vvYc](https://user-images.githubusercontent.com/105426840/235631512-024307cd-0b7a-442b-8581-7b9a957e1dda.jpg)

**Comment by bayaraa** [comment]
no no, i mean not glide mode ( `-3dfx` )
https://github.com/bayaraa/d2gl/wiki/Installation
> Run Game.exe without any flag will open game in DDraw mode (except 1.14d).
   Run Game.exe with -3dfx flag will open game in Glide mode (don't use -w flag).

**Comment by Vahsify** [comment]
> no no, i mean not glide mode ( `-3dfx` )

@bayaraa Yes, in ddraw mode works fine.
![kPRrABSi2vA](https://user-images.githubusercontent.com/105426840/235634867-af087739-143a-4c95-989b-cc4069d3f960.jpg)

**Comment by bayaraa** [comment]
[glide3x.zip](https://github.com/bayaraa/d2gl/files/11372420/glide3x.zip)
Try this.

**Comment by bayaraa** [comment]
disabling bloom, LUT, mini-map change anything?

**Comment by Vahsify** [comment]
> disabling bloom, LUT, mini-map change anything?

Nothing changes.

**Comment by bayaraa** [comment]
Okey. this is my last stand :D
try this [glide3x.zip](https://github.com/bayaraa/d2gl/files/11376424/glide3x.zip)

**Comment by Vahsify** [comment]
> try this [glide3x.zip](https://github.com/bayaraa/d2gl/files/11376424/glide3x.zip)

@bayaraa Sadly, it didn't help.

**Comment by bayaraa** [comment]
> Yes, in ddraw mode works fine.

working ddraw is from version 1.1.2?

**Comment by Vahsify** [comment]
> working ddraw is from version 1.1.2?

@bayaraa Yes.

**Comment by bayaraa** [comment]
try this [glide3x.zip](https://github.com/bayaraa/d2gl/files/11396540/glide3x.zip)

**Comment by Vahsify** [comment]
> try this [glide3x.zip](https://github.com/bayaraa/d2gl/files/11396540/glide3x.zip)

@bayaraa Didn't notice any changes. I noticed only that the texture of the town portal breaks textures.
![DeiPbboyLC0](https://user-images.githubusercontent.com/105426840/236214092-17f69d8c-1961-4860-b93a-8d1c04b66c47.jpg)
![9wOteVufNhg](https://user-images.githubusercontent.com/105426840/236214143-d0febd10-a7d4-4c4b-ab14-cd68d13beb24.jpg)

**Comment by bayaraa** [comment]
strange. did you have include other mods (dll)?
really getting out of options. try this [glide3x.zip](https://github.com/bayaraa/d2gl/files/11398328/glide3x.zip)

**Comment by Vahsify** [comment]
> did you have include other mods (dll)?

All the same. 

Without the .dll everything is the same. There are no problems with the GTX 960 with the same build.

**Comment by Ognyan1987** [comment]
@Vahsify  Have you tried running thr D2videtoTest in your Diablo II folder ?

**Comment by Vahsify** [comment]
> Have you tried running thr D2videtoTest in your Diablo II folder ?

@Ognyan1987 Yes, I tried, regardless of the choice, the result did not change.

**Comment by bayaraa** [comment]
@Vahsify how about this [glide3x.zip](https://github.com/bayaraa/d2gl/files/11460213/glide3x.zip) ?

**Comment by Vahsify** [comment]
> @Vahsify how about this [glide3x.zip](https://github.com/bayaraa/d2gl/files/11460213/glide3x.zip) ?

@bayaraa Yes, this version works great. Thank you very much for your work.
