### ISSUE TITLE
D2gl and Widescreen

### ISSUE THREAD

**Issue by RestDreams** [bayaraa/d2gl#61]
Hello. I have a strange problem with d2gl v. 1.1.2. Can't turn on widescreen. I did everything according to the instructions. It was possible to find out that the widescreen mode is enabled if you use the SGD2FreeResolution.json file from the old version 1.1.1. Should I be worried about this?

**Comment by xijin1337** [comment]
try new feature "stretched viewport"

**Comment by RestDreams** [comment]
> try new feature "stretched viewport"

When "stretched viewport" is enabled, it simply stretches the image to full screen, it looks disgusting. In version 1.1.1, everything was much neater, the black bars on the sides were removed, with the picture quality unchanged.

**Comment by RestDreams** [comment]
![Screenshot001](https://user-images.githubusercontent.com/132216627/235364675-d69fac42-7605-4d70-b44e-aa98c9826712.png)
![Screenshor001](https://user-images.githubusercontent.com/132216627/235364679-3da43df8-1b8d-43bb-b657-7390e2754c04.png)

For clarification. The first screenshot shows version 1.1.2 with "stretched viewport" enabled. In the second screenshot, version 1.1.2 with the SGD2FreeResolution.json file that was included in version 1.1.1

**Comment by bayaraa** [comment]
So what's the issue here?
> In the second screenshot, version 1.1.2 with the SGD2FreeResolution.json file that was included in version 1.1.1

second screenshot already in widescreen.

**Comment by RestDreams** [comment]
> So what's the issue here?
I don't know if this is a problem. To support widescreen mode, you need to take the json file from version 1.1.1. If you install version 1.1.2 without this file, widescreen mode will not be supported.

**Comment by bayaraa** [comment]
ahh.
**SGD2FreeResolution** is not my mod. I just built from source to support D2GL and included it's custom build in zip archive.
> Removed custom build SGD2FreeRes from zip archive.
Now you can download directly from https://github.com/mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Resolution.
Thanks to [Mir](https://github.com/mir-diablo-ii-tools/) to merging D2GL supported wrappers.

But like in release description from SGD2FreeRes v3.0.4.0 D2GL supported so i don't have to ship D2GL with it. Therefore you can download it or use included older version its up to you.

**Comment by RestDreams** [comment]
If the widescreen mode doesn't work without your custom build of SGD2FreeResolution, then it's not supported and the problem is in SGD2FreeResolution? Did I understand correctly?

**Comment by xijin1337** [comment]
@RestDreams 
[SGD2FreeRes.zip](https://github.com/bayaraa/d2gl/files/11362053/SGD2FreeRes.zip)

**Comment by RestDreams** [comment]
> @RestDreams [SGD2FreeRes.zip](https://github.com/bayaraa/d2gl/files/11362053/SGD2FreeRes.zip)
SGD2FreeRes.zip

I unpacked the file into the game folder. This should help?

**Comment by bayaraa** [comment]
Is SGD2FreeRes.dll added in D2GL's config file?
https://github.com/bayaraa/d2gl/wiki/Installation#widescreen

**Comment by RestDreams** [comment]
I have added the resolution in SGD2FreeResolution.json file. Everything works well. Apparently I'm dumb, it's not obvious that the "json" file format is opened by a text editor. But it worked out in the end, thanks.
