### ISSUE TITLE
Amazing work Bayaraa, the new update is running beautifully.

### ISSUE THREAD

**Issue by skylight102** [bayaraa/d2gl#62]
Also, I know you may see this as not a priority, but it would be so nice if the weather could be fixed in act 5.

To me, it is the last "big" obvious problem.

Much love for your efforts, I love it!

**Comment by skylight102** [comment]
> @skylight102 I have task for you. Could you try this build if it's running normally. Applied some cpu usage fix. [glide3x.zip](https://github.com/bayaraa/d2gl/files/11364545/glide3x.zip)

Doesn't seem happy with this at all mate, infact it is causing an instant crash upon load in for me, perhaps others can confirm.

**Comment by bayaraa** [comment]
@skylight102 oh man :(
could you provide me log files?

**Comment by Ognyan1987** [comment]
> > @skylight102 I have task for you. Could you try this build if it's running normally. Applied some cpu usage fix. [glide3x.zip](https://github.com/bayaraa/d2gl/files/11364545/glide3x.zip)
> 
> Doesn't seem happy with this at all mate, infact it is causing an instant crash upon load in for me, perhaps others can confirm.

Run d2Vid test as admin and compability mode windows xp sp 3 , run the video test and at the end select the glide 3dfx option and try to run the game again

**Comment by skylight102** [comment]
Sorry mate, I’ve been really busy last day or so, i will try in a few hours.

Thanks!

On 2 May 2023, at 19:02, Ognyan ***@***.***> wrote:

﻿

@skylight102<https://github.com/skylight102> I have task for you. Could you try this build if it's running normally. Applied some cpu usage fix. glide3x.zip<https://github.com/bayaraa/d2gl/files/11364545/glide3x.zip>

Doesn't seem happy with this at all mate, infact it is causing an instant crash upon load in for me, perhaps others can confirm.

Run d2Vid test as admin and compability mode windows xp sp 3 , run the video test and at the end select the glide 3dfx option and try to run the game again

**Comment by bayaraa** [comment]
> Doesn't seem happy with this at all mate, infact it is causing an instant crash upon load in for me, perhaps others can confirm.

ah. sorry previous build has mini-map bug which is insta crash when you enter game. my bad.
try this build for cpu fix.
[glide3x.zip](https://github.com/bayaraa/d2gl/files/11376424/glide3x.zip)

**Comment by skylight102** [comment]
hmmm, yes it now works, but the weather is still broken in act 5, is that what im testing here? :P

**Comment by skylight102** [comment]
[d2gl.log](https://github.com/bayaraa/d2gl/files/11377223/d2gl.log)

**Comment by bayaraa** [comment]
@skylight102 thanks. Its not weather fix. Its cpu usage fix build.

**Comment by skylight102** [comment]
Ah, I thought you had fixed that already :D

Although it's still not perfect (at least for my pc), what you have done is pretty close considering how old this game is.

You are a very clever human!

Let me know if you'd like me to do anything else.
