### ISSUE TITLE
Adding Custom Shaders

### ISSUE THREAD

**Issue by nanafy** [bayaraa/d2gl#63]
I love this repo. You made the game amazing. Couple this with internal high-resolution fix, and its jaw-droppingly good. I was wondering if there was a method of putting my own GLSL shader files into the drop-menu. I've looked high and low in the .ini files but dont see a method of doing so. Seems like everything is hardcoded.

**Comment by bayaraa** [comment]
Currently all upscale shaders hardcoded. Planned load shader externally in the future.

**Comment by nanafy** [comment]
Thank you, really looking forward to it.

**Comment by Ognyan1987** [comment]
Sorry for asking but is upscale shader a tool which makes the picture and more exactly the charcter ad enviroment non pixelated?

**Comment by MxCen** [comment]
It's enough for now.For me, Custom Shaders is not a required feature

**Comment by bayaraa** [comment]
since 1.3.0 d2gl uses custom shaders. see https://github.com/bayaraa/d2gl/wiki/Multi%E2%80%90Pass-shader-system
