### ISSUE TITLE
Finally got it running on wine

### ISSUE THREAD

**Issue by sgtrusty** [bayaraa/d2gl#64]
![image](https://user-images.githubusercontent.com/48886164/236528790-31998d63-3a09-4066-b951-f44fe6500ab8.png)
But the textures are showing up all black like this, only in character creation screen and in-game. Besides that, it plays perfectly.

I am using Arch Linux and wine with Vulkan on an AMD GPU. Just wondering if anybody has had this issue or a possible fix for it, I'm on a very complicated virtualization setup as it is and I understand if it will be difficult to work around.

**Comment by bayaraa** [comment]
No idea. Probably some driver issues.
I tested only Wine with Lutris on Ubuntu.

**Comment by sgtrusty** [comment]
No errors, just info messages.
> == D2GL logging started. (2023/5/11) ==
> 
> [01:23:57][INFO] Game version 1.13c detected.
> [01:23:57][INFO] Windows version 5.2 (build: 3790) detected.
> [01:23:57][INFO] Loading early DLLs.
> [01:23:57][INFO] Game requested screen size: 640 x 480
> [01:23:57][INFO] Window style switched to dark mode.
> [01:23:57][INFO] Switched to fullscreen mode: 1920 x 1080
> [01:23:57][INFO] OpenGL: 4.6 (RENOIR (renoir, LLVM 15.0.7, DRM 3.49, 6.1.24-hardened1-1-hardened))
> [01:23:57][INFO] OpenGL: GL_MAX_TEXTURE_IMAGE_UNITS = 32
> [01:23:57][INFO] OpenGL: Independent blending available.
> [01:23:57][INFO] Loading late DLLs.
> [01:23:57][INFO] SGD2FreeRes.dll loaded.
> [01:23:57][INFO] Applying custom size.
> [01:23:57][INFO] Game requested screen size: 800 x 600
> [01:23:57][INFO] Game requested screen size: 640 x 480
> [01:24:16][INFO] Applying custom size.
> [01:24:16][INFO] Game requested screen size: 800 x 600

Thanks for the help though

**Comment by sgtrusty** [comment]
![image](https://github.com/bayaraa/d2gl/assets/48886164/928a3871-a56a-4132-8dde-25cf386e99a0)
![image](https://github.com/bayaraa/d2gl/assets/48886164/bf6dce05-2b3c-40b1-8beb-51d351ddba0e)
Seems like UI textures are placing into the game screen too.

I'll post here again if I get it fixed somehow, the opengl seems to be working a lot better than the dx with the glide overrides... hope i can fix this lol. I am confident its something dealing my setup and/or wine

**Comment by sgtrusty** [comment]
These are some of the drivers I am using btw, with a Radeon gpu:
![image](https://github.com/bayaraa/d2gl/assets/48886164/6fb21541-15ac-4707-a9cf-47e978b9c615)
![image](https://github.com/bayaraa/d2gl/assets/48886164/25fc4027-da90-497b-8792-dd6010dcb62b)

**Comment by sgtrusty** [comment]
Couldn't get it fixed. Marking as resolved, will post comments if I workaround it in the future.
