### ISSUE TITLE
Enhancement request

### ISSUE THREAD

**Issue by skylight102** [bayaraa/d2gl#66]
It would be great if the large map, did not overlap the mini map, because I often use both (in situations where you need to see further, ie, where the summoner is on act 2). 

Sometimes you can tele and it looks a little confusing with the maps overlapping, especially when using the max scale mini map like I do.

Not sure if anyone else would like this feature, so let's see! : )

**Comment by jn64** [comment]
How about hiding the minimap when full map is open?

**Comment by skylight102** [comment]
That’s a good idea!

On 29 May 2023, at 15:19, jn64 ***@***.***> wrote:

﻿

How about hiding the minimap when full map is open?

**Comment by bayaraa** [comment]
this is resolved in v1.2.0.
