### ISSUE TITLE
Enhancement suggestion: Optional for minimize behavior

### ISSUE THREAD

**Issue by altoiddealer** [bayaraa/d2gl#80]
Hello, I've been using this other d2gl for awhile now (https://github.com/bolrog/d2dx)

I just tried your version and it is superior in many ways - the in-game menu, the HD text, HD cursor, etc.

However, there is a critical difference that makes this unusable for me.
-With bolrog's version, if I press the Windows key or Alt-Tab, the game minimizes.
-With your version
    -If I press the Windows key the task bar and Windows search simply steal focus, leaving D2 running.
    -If I press Alt-Tab, the game minimizes but part of the window replaces the task bar for some reason.
    

For my purposes, there needs to be a way to swiftly hide the game.
I imagine there are many others who share this sentiment

**Comment by bayaraa** [comment]
> For my purposes, there needs to be a way to swiftly hide the game.
I imagine there are many others who share this sentiment

you want to hide it faster when your boss came your office lol :P

**Comment by bayaraa** [comment]
added in 1.2.2

**Comment by MxCen** [comment]
you want to hide it faster when your boss came to your office lol :P
hahahaha~
