### ISSUE TITLE
Crash when click on Create Game

### ISSUE THREAD

**Issue by XpucPenchev** [bayaraa/d2gl#81]
Hi, when HD Text is on and click on Create Game the game grashes to desktop with no errors - just closes.

[D2Debug-230713.txt](https://github.com/bayaraa/d2gl/files/12043944/D2Debug-230713.txt)

**Comment by bayaraa** [comment]
MXL is not compatible currently.
Is it glide or ddraw?

**Comment by XpucPenchev** [comment]
It is glide

**Comment by Pooquer** [comment]
@XpucPenchev [https://github.com/Pooquer/d2gl-mxl/releases](https://github.com/Pooquer/d2gl-mxl/releases) does this work for you?

**Comment by XpucPenchev** [comment]
@Pooquer Yeah, works like a charm ! Thank you ! :)
