### ISSUE TITLE
Text Overlapping

### ISSUE THREAD

**Issue by DiabloRecon** [bayaraa/d2gl#83]
When HD Text option is enabled, with Resistances enabled in BH 1.9.9 the name field has overlapping text.
![Untitled](https://github.com/bayaraa/d2gl/assets/139571777/50b2ca93-973f-41e9-8ede-2e015f571b2c)
Played on vanilla Diablo II LOD with PlugY and BH 1.9.9

**Comment by bayaraa** [comment]
hi. I am aware of this issue. Right now nothing can do except uncheck it on BH menu or turn off hd text of d2gl completely.
i am thinking to change monster hp with extra informations.

**Comment by DiabloRecon** [comment]
Do you know when that could be fixed? Those resistances are important to me and the HD text is too good to turn it off.

**Comment by bayaraa** [comment]
No ETA.

**Comment by DiabloRecon** [comment]
All right. Keep up the good work.

**Comment by DiabloRecon** [comment]
Can you update on progress if there is any toward fixing this issue?

**Comment by bayaraa** [comment]
decided not make changes to hp bar. instead resistance numbers added above hp bar in 1.3.0.
