### ISSUE TITLE
The new map doesn't work properly

### ISSUE THREAD

**Issue by DiabloRecon** [bayaraa/d2gl#84]
The map in the corner which is added in D2GL appears to be cut off.
![2](https://github.com/bayaraa/d2gl/assets/139571777/a7ca7be6-2812-4001-bc31-7a3b167a8e43)

I play vanilla Diablo II LOD  on PlugY and BH 1.9.9

**Comment by bayaraa** [comment]
looks like you turned on minimap in esc menu?
If so it needs fullscreen map in order to work d2gl's minimap.

**Comment by DiabloRecon** [comment]
Yes I had a minimap, now I changed to fullscreen and the map works fine. Thanks.
