### ISSUE TITLE
DrawItemQuantity is not valid in Bnet mode

### ISSUE THREAD

**Issue by MxCen** [bayaraa/d2gl#87]
DrawItemQuantity is not valid in Bnet mode

ver 1.2.2

PVPGN-Bnet

**Comment by bayaraa** [comment]
What is not valid means?
Is it not drawing? Or its getting error?

Ps: I get reports that it doesn't work with basemod.

**Comment by MxCen** [comment]
“I did not use BASEMOD, it works normally in standalone mode, but the remaining quantity cannot be displayed under Bnet.” 😊

**Comment by MxCen** [comment]
“I did not use BASEMOD, it works normally in SP mode, but the remaining quantity cannot be displayed under Bnet.” 😊

**Comment by bayaraa** [comment]
just checked its not working in multiplayer so opening issue until it fixed

**Comment by MxCen** [comment]
{ D2DLL_D2CLIENT, { 0x95B7D }, PATCH_NOPBLOCK, FALSE, 5 },
{ D2DLL_D2CLIENT, { 0x95B7D }, PATCH_CALL, FALSE, 0 },
{ D2DLL_D2CLIENT, { 0x95B7D + 1 }, (DWORD)ShowItemCount, TRUE, 0 },
	
`UnitAny* __stdcall ShowItemCount(UnitAny* pItem)
{
	if (pItem && pItem->dwType == UNIT_ITEM && pItem->pItemData->InvPage != 0xFF)
	{
			......................
	}
	return D2COMMON_GetNextInventoryItem(pItem);
}`

**Comment by MxCen** [comment]
{ D2DLL_D2CLIENT, { 0x95B7D + 1 }, (DWORD)ShowItemCount, TRUE, 0 },

In order to avoid unnecessary trouble, I have done some tests on this address, and it can basically work normally in all modes. Maybe you can take a look?😊

**Comment by bayaraa** [comment]
thanks. i will use that address!

**Comment by MxCen** [comment]
Problem solving closed
