### ISSUE TITLE
Chinese HD text crash

### ISSUE THREAD

**Issue by MxCen** [bayaraa/d2gl#90]
After turning on HD text, when killing monsters and items fall to the ground and start rendering item names, if the mouse pointer points to the item, the game will occasionally crash.

1.13C

[Error Log.zip](https://github.com/bayaraa/d2gl/files/12091713/Error.Log.zip)

**Comment by bayaraa** [comment]
is it latest build (1.2.2)?
I remember i had same problem with previous builds.

**Comment by weili0677** [comment]
> is it latest build (1.2.2)? I remember i had same problem with previous builds.

may be 1.2.1? I compile from your sourcecode.

**Comment by MxCen** [comment]
1.2.1~~

**Comment by MxCen** [comment]
1.3.0 not crash
