### ISSUE TITLE
Some letters are replaced with a symbol in a different language version of D2

### ISSUE THREAD

**Issue by DiabloRecon** [bayaraa/d2gl#97]
In a polish version some letters are replaced with a symbol 
![Screenshot 2023-07-22 161907](https://github.com/bayaraa/d2gl/assets/139571777/645fd0e2-ded9-48fc-aeeb-5a5e5be6710e)

**Comment by bayaraa** [comment]
Sad face means that glyph is missing from font atlas.
i tested official polish with 1.14d and everything was normal.
What characters would those sad face?

**Comment by DiabloRecon** [comment]
I use 1.13c version. The letters on the screenshots which are replaced with symbols are " ż  ś ę ń "

**Comment by bayaraa** [comment]
font changed in 1.3.1 for polish client. should display all characters now.
